import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GithubIcon, LinkedinIcon } from "./components/icons";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	console.log("LAYOUT")
	return (
		<html lang="en">
			<body className={inter.className}>{children}
				<footer className="w-full min-h-20 py-10 px-4 bg-purple-100 mt-8 flex flex-col justify-center">
					<section className="flex flex-row justify-around">
						<h2 className="text-purple-600 font-semibold text-xl">Ask</h2>
						<a href="https://github.com/DreckSallow/qa-web">
							<GithubIcon className="h-8 w-8 fill-gray-700" />
						</a>
						<a href="https://github.com/DreckSallow/qa-web">
							<LinkedinIcon className="h-8 w-8 fill-gray-700" />
						</a>{" "}
					</section>
					<span className="text-sm text-center mt-8">
						&copy; 2023 Dreck Sallow. All Rights Reserved
					</span>
				</footer>
			</body>

		</html>
	);
}
